In [4]:
pip install tensorflow -U

Defaulting to user installation because normal site-packages is not writeable
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 2.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/377.0 MB 4.5 MB/s eta 0:01:25
   ---------------------------------------- 0.2/377.0 MB 2.5 MB/s eta 0:02:33
   ---------------------------------------- 0.3/377.0 MB 3.3 MB/s eta 0:01:55
   ---------------------------------------- 0.5/377.0 MB 3.5 MB/s eta 0:01:48
   ---------------------------------------- 0.6/377.0 MB 3.4 MB/s eta 0:01:51
   ---------------------------------------- 0.8/377.0 MB 3.8 MB/s eta 0:01:39
   ---------------------------------------- 1.2/377.0 MB 4.6 MB/s eta 0:01:22
   ---------------------------------------- 1.4/377

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [5]:
# Create tensors
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [6]:
a[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
# Create tensors
x = tf.constant([[1,2,3],[7,8,9]])
y = tf.constant([[4,5],[6,2]])

print("Tensor a:",x)
print("Tensor b:",y)

Tensor a: tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)
Tensor b: tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [9]:
# Create tensors
x = tf.constant([[1,2,3],[7,8,9]], dtype=np.int8)
y = tf.constant([[4,5],[6,2]])

print("Tensor a:",x)
print("Tensor b:",y)

Tensor a: tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int8)
Tensor b: tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [12]:
# Create tensors
x = tf.constant([[[1,2,3],[7,8,9]],[[0,2,5],[7,6,8]]], dtype=np.int8)
y = tf.constant([[4,5],[6,2]])

print("Tensor a:",x)
print("Tensor b:",y)

Tensor a: tf.Tensor(
[[[1 2 3]
  [7 8 9]]

 [[0 2 5]
  [7 6 8]]], shape=(2, 2, 3), dtype=int8)
Tensor b: tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [13]:
#Add tensor
c = tf.add(a,b)
print("addition:",c)

addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [14]:
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [15]:
# Subtract tensor
d = tf.subtract(a,b)
print("Subtraction:",d)

Subtraction: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [16]:
a-b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [18]:
d.numpy()

array([-3, -3, -3])

In [19]:
a.numpy()

array([1, 2, 3])

In [20]:
# Multiply tensors
e = tf.multiply(a,b)
print("Multiplication:",e)

Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [21]:
a*b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [22]:
# Divide tensors
f = tf.divide(a,b)
print("Division:",f)

Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [23]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [24]:
a//b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [25]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [26]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [27]:
# Matrix multiplication
a_matrix = tf.constant([[1,2],[3,4]])
b_matrix = tf.constant([[5,6],[7,8]])

g = tf.matmul(a_matrix,b_matrix)
print("Matrix Multiplication:",g)

Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
tf.